// @ts-check
import nextConfig from '@sab/config/eslint/next';

export default [
  {
    // next-env.d.ts is auto-generated by Next and uses triple-slash refs.
    ignores: ['next-env.d.ts', '.next/**'],
  },
  ...nextConfig,
];
